import type { SiteContent } from "@/content/types";

export const tr = {
  languageName: "Türkçe",
  metadata: {
    title: "NIMAY — Bağımsız Dijital Stüdyo",
    description: "NIMAY, stratejiden geliştirmeye marka kimlikleri ve web siteleri tasarlayan bağımsız bir dijital stüdyodur. Türkiye merkezli, dünyaya açık.",
    ogTitle: "NIMAY — Bağımsız Dijital Stüdyo",
    ogDescription: "NIMAY, stratejiden geliştirmeye marka kimlikleri ve web siteleri tasarlayan bağımsız bir dijital stüdyodur. Türkiye merkezli, dünyaya açık.",
    ogLocale: "tr_TR",
    alternateLocale: "en_US",
    imageAlt: "NIMAY — Bağımsız Dijital Stüdyo",
  },
  labels: {
    home: "Ana sayfa", work: "İşler", contact: "İletişim", language: "Dil", menu: "Menü", close: "Kapat", navigation: "Ana navigasyon", mobileNavigation: "Mobil navigasyon", skipToContent: "İçeriğe geç", basedIn: "Türkiye merkezli", workingWorldwide: "Dünyaya açık", selectedWork: "Seçili İşler", projectCount: "01—02", services: "Hizmetler", sector: "Sektör", year: "Yıl", viewProject: "Projeyi görüntüle", conceptWebsite: "Konsept Web Sitesi", engagements: "Hizmet modelleri", websiteEngagements: "Web sitesi çalışmaları.", typicalTimeline: "Tahmini süre", terms: "Koşullar", approach: "Yaklaşım", studio: "Stüdyo", capabilities: "Yetkinlikler", contactPrompt: "Yeni bir kimlik veya web sitesi mi planlıyorsunuz?", copyEmail: "E-postayı kopyala", emailCopied: "E-posta kopyalandı", privacy: "Gizlilik", privacyPreferences: "Gizlilik tercihleri", analyticsPreferences: "Analiz tercihleri", allowAnalytics: "Analizlere izin ver", rejectAnalytics: "Reddet", analyticsDescription: "Site kullanımını ölçmemize yardımcı olması için analizlere izin verin veya isteğe bağlı analizleri kapalı tutmak için reddedin. Seçiminiz bu cihazda saklanır ve istediğiniz zaman değiştirilebilir.", footerStudioDescriptor: "Bağımsız Dijital Stüdyo", viewProjectAria: "Konsept web sitesini görüntüle",
    pricePrefix: "Başlangıç",
  },
  hero: { kicker: "NIMAY / Bağımsız Dijital Stüdyo", title: "Stratejiden geliştirmeye, marka kimlikleri ve web siteleri.", location: "Türkiye merkezli\nDünyaya açık" },
  selectedWork: { framing: "Dijital yaklaşım, tasarım ve geliştirme anlayışımızı yansıtan bağımsız konsept çalışmaları." },
  projects: {
    "zera-moda": { projectType: "Gelinlik web sitesi", description: "Koleksiyon keşfini yönlendirilmiş özel prova talebiyle birleştiren bir gelinlik web sitesi konsepti.", services: ["Web sitesi tasarımı / Geliştirme / Sanat yönetimi"], industry: "Moda" },
    "erbay-ekinci": { projectType: "Couture atölyesi web sitesi", description: "Koleksiyon hikâyeleri, atölye detayları ve net bir randevu talebi akışı sunan İstanbul merkezli haute couture web sitesi konsepti.", services: ["Web sitesi tasarımı / Sanat yönetimi / Geliştirme"], industry: "Haute Couture" },
  },
  engagements: {
    essential: { audience: "Bağımsız profesyoneller, küçük premium işletmeler ve odaklı hizmet işletmeleri için.", timelineLabel: "7–10 iş günü", scopeLabel: "Dahil olanlar", scope: ["Strateji ve keşif", "Bilgi mimarisi", "Özel web sitesi tasarımı", "Duyarlı geliştirme", "1–3 ana sayfa/görünüm", "Teknik SEO kurulumu", "İletişim / CTA kurulumu", "Duyarlı QA ve yayına alma", "2 revizyon turu dahil", "Teslim edilen çalışmaya ilişkin 30 gün teknik hata desteği"] },
    signature: { audience: "Çok sayfalı bir web sitesine, daha derin bir içerik yapısına, güçlü bir sanat yönetimine, projeye özel etkileşimlere ve daha özenli bir iletişim sürecine ihtiyaç duyan yerleşik markalar için.", timelineLabel: "10–15 iş günü", scopeLabel: "Dahil olanlar", scope: ["Strateji ve keşif", "Derinlemesine bilgi mimarisi", "4–8 ana sayfa/görünüm için özel tasarım", "Güçlü sanat yönetimi", "Projeye özel etkileşim detayları", "Gelişmiş iletişim / talep akışı", "Teknik SEO kurulumu", "Duyarlı QA ve yayına alma", "2 revizyon turu dahil", "Teslim edilen çalışmaya ilişkin 30 gün teknik hata desteği"] },
    "custom-b2b": { audience: "Üreticiler, ihracatçılar, büyük şirketler, katalog ağırlıklı işletmeler, çok dilli veya uluslararası işletmeler ve nitelikli talep toplamaya ihtiyaç duyan şirketler için.", timelineLabel: "Kapsama bağlı olarak 3–6 hafta.", scopeLabel: "Olası kapsam", scopeIntro: "Ürün ve katalog mimarisinden çok dilli içeriğe, nitelikli taleplerden özel entegrasyonlara uzanan daha karmaşık ticari operasyonlar için dijital sistemler.", scope: ["Özel bilgi mimarisi", "Ürün / katalog yapısı", "Çok dilli mimari", "Nitelikli talep formları", "Distribütör / toptan satış / B2B akışları", "Özel entegrasyonlar", "Daha geniş içerik yapıları", "İhtiyaca göre teknik gereksinimler"], note: "Nihai kapsam, revizyon hakkı ve yayına alma sonrası destek teklif kapsamında belirlenir." },
  },
  approachHeading: "Nasıl çalışıyoruz?",
  approach: [{ title: "Yön Belirleme", description: "İşi, hedef kitleyi ve kısıtları tanırız. Sitenin ne anlatması ve ne yapması gerektiğini birlikte netleştiririz." }, { title: "Tasarım", description: "Görsel sistemi ve sayfa yapısını kurar, geliştirme öncesinde temel etkileşimleri rafine ederiz." }, { title: "Geliştirme", description: "Onaylanan tasarımı duyarlı bir web sitesine dönüştürür, teslim öncesinde sayfaları ve etkileşimleri test ederiz." }],
  studioStatement: "Bir web sitesi markayı netleştirmeli ve bir sonraki adımı görünür kılmalı.",
  capabilities: [{ title: "Strateji", items: ["Konumlandırma / Marka yönü"] }, { title: "Kimlik", items: ["Görsel kimlik / Sanat yönetimi"] }, { title: "Dijital", items: ["Web sitesi tasarımı / Geliştirme"] }],
  contact: { heading: "Yeni bir kimlik veya web sitesi mi planlıyorsunuz?", guidance: "İşinizi, mevcut web siteniz varsa onu, yeni sitenin ne başarmasını istediğinizi ve tercih ettiğiniz takvimi kısaca anlatın. Kapsamı netleştirmek için sonraki adımları ve ihtiyaç duyduğumuz soruları sizinle paylaşacağız.", location: "Türkiye merkezli · Dünyaya açık" },
  privacy: { kicker: "NIMAY / Gizlilik", title: "Gizlilik ve analiz", updated: "Son güncelleme: Eylül 2026", sections: [{ number: "01", title: "İsteğe bağlı analizler", paragraphs: ["NIMAY, Google Analytics 4’ü (GA4) yalnızca açıkça izin vermeniz halinde kullanır. Bu seçimi yapmadan önce GA4 yüklenmez ve herhangi bir analiz isteği gönderilmez. Analizleri reddederseniz GA4 devre dışı kalır.", "Seçiminiz tarayıcınızda yerel olarak saklanır. Alt bilgideki gizlilik tercihleri üzerinden seçiminizi istediğiniz zaman yeniden açıp değiştirebilirsiniz."] }, { number: "02", title: "Analiz izni verirseniz", paragraphs: ["Google Analytics, analiz çerezleri yerleştirebilir ve görüntülenen sayfalar, cihaz ve tarayıcı bilgileri, IP adresinizden türetilen yaklaşık konum ve etkileşim verileri gibi standart kullanım bilgilerini toplayabilir. NIMAY, isim, e-posta adresi veya diğer doğrudan kişisel tanımlayıcıları Google Analytics’e bilerek göndermez.", "Reklam sinyalleri mevcut uygulamada kapalıdır. NIMAY, Google Ads, yeniden pazarlama veya kullanıcı kimlikleri kullanmaz."] }, { number: "03", title: "Tarayıcı depolaması", paragraphs: ["Analiz tercihiniz daha sonraki ziyaretlerde hatırlanması için tarayıcınızın yerel depolama alanına kaydedilir. Site, temel işlevlerin çalışması için teknik olarak gerekli tarayıcı veya depolama mekanizmalarını da kullanabilir."] }], contactLabel: "İletişim", contactHeading: "Gizlilik hakkında sorularınız mı var?" },
  notFound: { kicker: "NIMAY STUDIO / 404", title: "Sayfa bulunamadı.", home: "Ana sayfaya dön" },
  terms: ["Başlangıçta %50 / nihai üretim tesliminden önce %50 ödeme.", "Ek kapsam ayrıca fiyatlandırılır.", "Alan adı, ücretli üçüncü taraf hizmetleri ve profesyonel fotoğraf/video gibi üretim maliyetleri ayrıca teklif edilmedikçe dahil değildir.", "Sürekli SEO, reklam, e-ticaret/ödeme sistemleri, çeviri ve devam eden bakım ayrı kapsamlardır.", "Dahil olan 30 günlük destek, teslim edilen çalışmadaki teknik hataları kapsar; sınırsız tasarım veya içerik değişikliğini kapsamaz."],
} as const satisfies SiteContent;
