export const engagements = [
  {
    number: "01",
    name: "Essential",
    price: "Starting at ₺19.900",
    audience: "For independent professionals, small premium businesses and focused service businesses.",
    timeline: "7–10 business days",
    scopeLabel: "Include",
    scope: [
      "Strategy and discovery",
      "Information architecture",
      "Custom website design",
      "Responsive development",
      "1–3 primary pages/views",
      "Technical SEO setup",
      "Contact / CTA setup",
      "Responsive QA and launch deployment",
      "2 revision rounds included",
      "30 days of technical bug support",
    ],
  },
  {
    number: "02",
    name: "Signature",
    price: "Starting at ₺34.900",
    audience: "For established brands that need a multi-page website with deeper content structure, stronger art direction, tailored interactions and a more considered enquiry journey.",
    timeline: "10–15 business days",
    scopeLabel: "Include",
    scope: [
      "Strategy and discovery",
      "Deeper information architecture",
      "Custom design across 4–8 primary pages/views",
      "Stronger art direction",
      "Tailored interaction details",
      "Advanced enquiry/contact flow",
      "Technical SEO setup",
      "Responsive QA and launch deployment",
      "2 revision rounds included",
      "30 days of technical bug support",
    ],
  },
  {
    number: "03",
    name: "Custom / B2B",
    price: "Starting at ₺49.900",
    audience: "For manufacturers, exporters, larger companies, catalog-heavy businesses, multilingual or international businesses and companies needing qualified lead capture.",
    timeline: "3–6 weeks depending on scope.",
    scopeLabel: "Possible scope",
    scopeIntro: "Digital systems for more complex commercial operations — from product and catalog architecture to multilingual content, qualified enquiries and custom integrations.",
    scope: [
      "Custom information architecture",
      "Product / catalog structure",
      "Multilingual architecture",
      "Qualified enquiry forms",
      "Distributor / wholesale / B2B flows",
      "Custom integrations",
      "Larger content structures",
      "Tailored technical requirements",
    ],
    note: "Final scope, revision allowance and post-launch support are defined in the proposal.",
  },
] as const;

export const engagementTerms = [
  "50% upfront to begin / 50% before final production handoff.",
  "Additional scope is quoted separately.",
  "Domain, paid third-party services and production costs such as professional photography/video are not included unless quoted.",
  "Ongoing SEO, advertising, ecommerce/payment systems, translation and ongoing maintenance are separate scopes.",
  "30-day included support covers technical bugs in delivered work, not unlimited design/content changes.",
] as const;
