/* WebGL hero: akışkan form. Taslaktaki shader kodu olduğu gibi taşındı. */
export const VS = 'attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}'

export const FS = [
  'precision highp float;',
  'uniform vec2 uRes;uniform float uT;uniform vec2 uM;uniform float uS;',
  'uniform vec3 uA,uB,uC,uD;',
  'float smin(float a,float b,float k){float h=max(k-abs(a-b),0.)/k;return min(a,b)-h*h*k*.25;}',
  'float map(vec3 p){',
  ' float t=uT*.5;',
  ' vec3 c0=vec3(sin(t*.7)*.12,cos(t*.6)*.08,0.);',
  ' vec3 c1=vec3(uM.x,uM.y,0.);',
  ' vec3 c2=vec3(cos(t*.9)*.55,sin(t*1.1)*.4,.1);',
  ' vec3 c3=vec3(sin(t*.8+2.)*.5,cos(t*.7+1.)*.45,-.1);',
  ' float d=length(p-c0)-.42;',
  ' d=smin(d,length(p-c1)-.26,.35);',
  ' d=smin(d,length(p-c2)-.2,.35);',
  ' d=smin(d,length(p-c3)-.16,.3);',
  ' d+=.018*sin(p.x*7.+t*2.)*sin(p.y*6.-t*1.6)*sin(p.z*7.+t);',
  ' return d;}',
  'vec3 nor(vec3 p){vec2 e=vec2(.002,-.002);return normalize(e.xyy*map(p+e.xyy)+e.yyx*map(p+e.yyx)+e.yxy*map(p+e.yxy)+e.xxx*map(p+e.xxx));}',
  'vec3 env(vec3 d){',
  ' float y=d.y*.5+.5;',
  ' vec3 c=mix(uC,uB,smoothstep(.0,.5,y));c=mix(c,uA,smoothstep(.5,.95,y));',
  ' c*=mix(.35,1.,smoothstep(-.03,.03,d.y));',
  ' float l1=smoothstep(.82,.86,dot(d,normalize(vec3(.6,.7,-.4))));',
  ' float l2=smoothstep(.9,.93,dot(d,normalize(vec3(-.7,.2,-.7))));',
  ' float st=smoothstep(.35,.4,abs(sin(d.x*5.+d.y*1.5)))*smoothstep(-.2,.3,d.y)*.0;',
  ' c+=vec3(1.)*l1*1.4+uD*l2*1.8+st;',
  ' return c;}',
  'void main(){',
  ' vec2 uv=(gl_FragCoord.xy-.5*uRes)/uRes.y;',
  ' uv.y-=.1;uv/=uS;',
  ' vec3 ro=vec3(0.,0.,-3.),rd=normalize(vec3(uv,1.6));',
  ' float b=dot(ro,rd);float cc=dot(ro,ro)-1.9;float h=b*b-cc;',
  ' if(h<0.){gl_FragColor=vec4(0.);return;}',
  ' float t=-b-sqrt(h);float hit=0.;',
  ' for(int i=0;i<56;i++){vec3 p=ro+rd*t;float d=map(p);if(d<.0015){hit=1.;break;}t+=d;if(t>6.)break;}',
  ' if(hit<.5){gl_FragColor=vec4(0.);return;}',
  ' vec3 p=ro+rd*t;vec3 n=nor(p);',
  ' vec3 r=reflect(rd,n);',
  ' float fr=pow(1.-max(dot(-rd,n),0.),3.);',
  ' vec3 col=env(r)*(.78+.5*fr);',
  ' col+=uD*fr*.35;',
  ' col=pow(col,vec3(.92));',
  ' gl_FragColor=vec4(col,1.);}'
].join('\n')
